/** 模型 id（工具报的、名单里写的、交接里自己写的）→ 给人看的名字。 */
export const NAMES: [string, string][] = [
  ['gpt-6-sol', 'GPT-6 Sol'],
  ['GPT-6', 'GPT-6'],
  ['gpt-5.3-codex-high-fast', 'GPT-5.3 Codex'],
  ['claude-opus-5-5', 'Claude Opus 5.5'],
  ['opus', 'Claude Opus'],
  ['Claude Opus 4.6 (Thinking)', 'Claude Opus 4.6'],
  ['claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'],
  ['claude-sonnet-4-20250514', 'Claude Sonnet 4'],
  ['claude-fable-5-1', 'Claude Fable 5.1'],
  ['cursor-grok-4.6-high-fast', 'Grok 4.6'],
  ['grok-4.7-high-fast', 'Grok 4.7'],
  ['Grok 4.6 Fast', 'Grok 4.6'],
  ['deepseek-flash', 'DeepSeek Flash'],
  ['deepseek-flash[1m]', 'DeepSeek Flash'],
  ['deepseek/deepseek-flash', 'DeepSeek Flash'],
  ['deepseek-v4-pro', 'DeepSeek V4 Pro'],
  ['GLM-5.3', 'GLM-5.3'],
  ['mimo-v2.6-pro', 'MiMo V2.6 Pro'],
  ['gemini-3.7-flash-high', 'Gemini 3.7 Flash'],
  ['kimi-k2', 'Kimi K2'],
  ['qwen3-coder-plus', 'Qwen3 Coder Plus'],
  ['', ''],
];
